name: espanso_gui_v2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  auto_size_text_field: ^2.2.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  pluto_grid: ^8.0.0
  rich_text_controller: ^2.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

  overflow_tab_bar:
    path: packages/overflow_tab_bar

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

